In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import requests
from bs4 import BeautifulSoup
from pattern import web
from fnmatch import fnmatch


# set some nicer defaults for matplotlib
from matplotlib import rcParams

In [6]:
from urllib.request import urlopen
#your code here    
def get_poll_xml(poll_id):
    link = 'http://charts.realclearpolitics.com/charts/'+ str(poll_id) +'.xml'
    xml = requests.get(link).text
    return xml
    
xml = get_poll_xml(1171)

In [25]:
def rcp_poll_data1(xml):
    dom = web.Element(xml)
    dates = dom.by_tag('series')[0]
    dates = {n.attributes['xid']:str(n.content) for n in dates.by_tag('value')}
    keys = dates.keys()
    result= {}
    result['Dates'] = pd.to_datetime([dates[k] for k in keys])
    for graph in dom.by_tag('graph'):
        title = graph.attributes['title']
        data = {v.attributes['xid']:float(v.content) if v.content else np.nan for v in graph.by_tag('value')}
        result[title] = [data[k] for k in keys]
    df = pd.DataFrame(result)
    return df
rcp_poll_data1(xml)

         Dates  Obama  Romney
0   2011-02-01   47.5    41.5
1   2011-02-02   47.5    41.5
2   2011-02-03   47.5    41.5
3   2011-02-04   47.5    41.5
4   2011-02-05   47.5    41.5
5   2011-02-06   47.5    41.5
6   2011-02-07   46.4    42.0
7   2011-02-08   46.4    42.0
8   2011-02-09   46.7    42.7
9   2011-02-10   46.7    42.7
10  2011-02-11   47.3    42.0
11  2011-02-12   47.3    42.0
12  2011-02-13   47.3    42.0
13  2011-02-14   47.3    42.0
14  2011-02-15   47.3    42.0
15  2011-02-16   47.0    41.7
16  2011-02-17   47.0    41.7
17  2011-02-18   47.0    41.7
18  2011-02-19   47.0    41.7
19  2011-02-20   47.0    41.7
20  2011-02-21   47.0    41.7
21  2011-02-22   47.0    41.7
22  2011-02-23   47.3    42.8
23  2011-02-24   47.3    42.8
24  2011-02-25   47.3    42.8
25  2011-02-26   47.3    42.8
26  2011-02-27   47.3    42.8
27  2011-02-28   47.3    42.8
28  2011-03-01   47.3    42.8
29  2011-03-02   47.6    42.4
..         ...    ...     ...
622 2012-10-15   47.3    47.4
623 2012-10-16   47.0    47.4
624 2012-10-17   47.0    47.4
625 2012-10-18   46.7    47.7
626 2012-10-19   47.1    47.0
627 2012-10-20   47.1    47.0
628 2012-10-21   47.1    46.9
629 2012-10-22   47.2    47.6
630 2012-10-23   47.1    48.0
631 2012-10-24   47.2    47.8
632 2012-10-25   47.0    47.9
633 2012-10-26   47.0    47.9
634 2012-10-27   46.9    47.9
635 2012-10-28   46.8    47.7
636 2012-10-29   46.8    47.6
637 2012-10-30   47.1    47.9
638 2012-10-31   47.4    47.4
639 2012-11-01   47.4    47.3
640 2012-11-02   47.4    47.3
641 2012-11-03   47.4    47.2
642 2012-11-04   47.9    47.4
643 2012-11-05   48.8    48.1
644 2012-11-06   48.8    48.1
645 2012-11-07    NaN     NaN
646 2012-11-08    NaN     NaN
647 2012-11-09    NaN     NaN
648 2012-11-10    NaN     NaN
649 2012-11-11    NaN     NaN
650 2012-11-12    NaN     NaN
651 2012-11-13    NaN     NaN

[652 rows x 3 columns]

In [37]:
html = requests.get('https://www.realclearpolitics.com/epolls/2010/governor/2010_elections_governor_map.html').text
def find_governor_races(html):
    dom = web.Element(html)
    pattern = 'http://www.realclearpolitics.com/epolls/????/governor/??/*-*.html'
    links = [a.attributes.get('href',"") for a in dom.by_tag('a')]
    links = [l for l in links if fnmatch(l,pattern)]
    links = list(set(links))
    return links
find_governor_races(html)

['http://www.realclearpolitics.com/epolls/2009/governor/nj/new_jersey_governor_corzine_vs_christie-1051.html',
 'http://www.realclearpolitics.com/epolls/2009/governor/va/virginia_governor_mcdonnell_vs_deeds-1055.html']